<?php  //[STAMP] 2fe25dcbff1a08333e986501820df456
namespace PhpUnitGen\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use PhpUnitGen\Tests\Helper\Acceptance;

trait AcceptanceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
