<?php
namespace PhpUnitGen\Tests\Utility;

use PhpUnitGen\Utility\ClassNameUtility;

/**
 * Class ClassNameUtilityTest
 * @package PhpUnitGen\Tests\Utility
 */
class ClassNameUtilityTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function shouldReturnAValidClassNameWithNamespaces() {
        $className = ClassNameUtility::getClassNameFromFile('tests/_data/Fixture/Classes/MyVendor/MyName/MyPool.php');
        $this->assertSame('MyVendor\MyName\MyPool', $className);
    }

    /**
     * @test
     */
    public function shouldReturnAValidClassName() {
        $className = ClassNameUtility::getClassNameFromFile('tests/_data/Fixture/Classes/MySecondPool.php');
        $this->assertSame('MySecondPool', $className);
    }

    /**
     * @test
     */
    public function shouldReturnNullOnInvalidClassFile() {
        $className = ClassNameUtility::getClassNameFromFile('tests/_data/dump.sql');
        $this->assertNull($className);
    }
}